### ISSUE TITLE
Add support for other collection types than List

### ISSUE THREAD

**Issue by gunnarmorling** [poetix/vaporetto#1]
Nice approach for a builder!

I've noticed that a `ClassCastException` is raised when changing the type of  `addressLines` from `List` to `Set`. You'd likely have to choose an implementation type based on the type of the referenced property.

Also support for `Map`-typed properties would be cool.

**Comment by poetix** [comment]
Resolved for Set. Maps are a slightly different matter - I might implement a k1, v1, k2, v2... style solution in the future.
